name: Auto Deploy Preview

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  checks: read

jobs:
  signal:
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch to App
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "auto-deploy",
              client_payload: {
                base: context.payload.before,
                head: context.sha,
                branch: context.ref.replace("refs/heads/", ""),
                repo: `${context.repo.owner}/${context.repo.repo}`
              }
            })
      - name: Wait for World Forge check run
        uses: actions/github-script@v7
        with:
          script: |
            const name = "World Forge Auto-Deploy";
            const owner = context.repo.owner, repo = context.repo.repo, ref = context.sha;
            const initDeadline = Date.now() + 2*60*1000;   // 2m to see the check appear
            const hardDeadline = Date.now() + 45*60*1000;  // 45m max runtime

            const sleep = (ms) => new Promise(r => setTimeout(r, ms));

            // Phase 1: wait for the check to appear
            while (Date.now() < initDeadline) {
              const { data } = await github.rest.checks.listForRef({ owner, repo, ref });
              const run = data.check_runs.find(c => c.name === name);
              if (run) break;
              await sleep(5000);
            }
            // If the check never appeared, fail early
            {
              const { data } = await github.rest.checks.listForRef({ owner, repo, ref });
              const run = data.check_runs.find(c => c.name === name);
              if (!run) {
                core.setFailed("Auto-deploy app did not initialize (no check run created).");
                return;
              }
            }

            // Phase 2: wait for completion
            while (Date.now() < hardDeadline) {
              const { data } = await github.rest.checks.listForRef({ owner, repo, ref });
              const run = data.check_runs.find(c => c.name === name);
              if (run?.status === "completed") {
                if (run.conclusion !== "success") core.setFailed(run.output?.summary || "Auto-deploy failed");
                return;
              }
              await sleep(10000);
            }
            core.setFailed("Timed out waiting for auto-deploy result.");
            
            