name: Auto Deploy Preview

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  statuses: read

jobs:
  auto-deploy:
    uses: Argus-Labs/world-cli/.github/workflows/auto_deploy.yaml@v1
    secrets: inherit
    with:
      base: ${{ github.event.before }}
      head: ${{ github.sha }}
