name: Auto Deploy Preview

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  statuses: read

jobs:
  auto-deploy:
    uses: Doglightning/testdeploystuff/.github/workflows/auto_deploy.yml@v1
    secrets: inherit
    with:
      base: ${{ github.event.before }}
      head: ${{ github.sha }}
