name: Auto Deploy Signal

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  signal:
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch to App
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "auto-deploy", // This becomes payload.Action
              client_payload: {
                base: context.payload.before,    // previous commit SHA
                head: context.sha,               // current commit SHA  
                branch: context.ref.replace("refs/heads/", ""),
                repo: `${context.repo.owner}/${context.repo.repo}`
              }
            })